In [2]:
import pandas as pd

In [3]:
books = pd.read_csv('/Users/juanmanrique/Documents/numpy_pandas/bestsellers with categories.csv', header=0, sep=",")

In [4]:
books

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [6]:
# Cual es el conteo por genero
'''
Cabe resaltar que cuando se realiza la agrupación el común se vuelve el indice
'''
books.groupby('Genre').count()

             Name  Author  User Rating  Reviews  Price  Year
Genre
Fiction       240     240          240      240    240   240
Non Fiction   310     310          310      310    310   310

In [7]:
books.groupby('Author').max()

,Name,User Rating,Reviews,Price,Year,Genre
Author,,,,,,
Abraham Verghese,Cutting for Stone,4.6,4866,11,2011,Fiction
Adam Gasiewski,Milk and Vine: Inspirational Quotes From Class...,4.4,3113,6,2017,Non Fiction
Adam Mansbach,Go the F**k to Sleep,4.8,9568,9,2011,Fiction
Adir Levy,What Should Danny Do? (The Power to Choose Ser...,4.8,8170,13,2019,Fiction
Admiral William H. McRaven,Make Your Bed: Little Things That Can Change Y...,4.7,10199,11,2017,Non Fiction
...,...,...,...,...,...,...
Walter Isaacson,Steve Jobs,4.6,7827,21,2017,Non Fiction
William Davis,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",4.4,7497,6,2013,Non Fiction
William P. Young,The Shack: Where Tragedy Confronts Eternity,4.6,19720,8,2017,Fiction
Wizards RPG Team,Player's Handbook (Dungeons & Dragons),4.8,16990,27,2019,Fiction
Zhi Gang Sha,Soul Healing Miracles: Ancient and New Sacred ...,4.6,220,17,2013,Non Fiction

In [8]:
books.groupby('Author').count()

                            Name  User Rating  Reviews  Price  Year  Genre
Author
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [10]:
books.groupby('Author').max()

,Name,User Rating,Reviews,Price,Year,Genre
Author,,,,,,
Abraham Verghese,Cutting for Stone,4.6,4866,11,2011,Fiction
Adam Gasiewski,Milk and Vine: Inspirational Quotes From Class...,4.4,3113,6,2017,Non Fiction
Adam Mansbach,Go the F**k to Sleep,4.8,9568,9,2011,Fiction
Adir Levy,What Should Danny Do? (The Power to Choose Ser...,4.8,8170,13,2019,Fiction
Admiral William H. McRaven,Make Your Bed: Little Things That Can Change Y...,4.7,10199,11,2017,Non Fiction
...,...,...,...,...,...,...
Walter Isaacson,Steve Jobs,4.6,7827,21,2017,Non Fiction
William Davis,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",4.4,7497,6,2013,Non Fiction
William P. Young,The Shack: Where Tragedy Confronts Eternity,4.6,19720,8,2017,Fiction
Wizards RPG Team,Player's Handbook (Dungeons & Dragons),4.8,16990,27,2019,Fiction
Zhi Gang Sha,Soul Healing Miracles: Ancient and New Sacred ...,4.6,220,17,2013,Non Fiction

In [11]:
books.groupby('Author').min()

,Name,User Rating,Reviews,Price,Year,Genre
Author,,,,,,
Abraham Verghese,Cutting for Stone,4.6,4866,11,2010,Fiction
Adam Gasiewski,Milk and Vine: Inspirational Quotes From Class...,4.4,3113,6,2017,Non Fiction
Adam Mansbach,Go the F**k to Sleep,4.8,9568,9,2011,Fiction
Adir Levy,What Should Danny Do? (The Power to Choose Ser...,4.8,8170,13,2019,Fiction
Admiral William H. McRaven,Make Your Bed: Little Things That Can Change Y...,4.7,10199,11,2017,Non Fiction
...,...,...,...,...,...,...
Walter Isaacson,Leonardo da Vinci,4.5,3014,20,2011,Non Fiction
William Davis,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",4.4,7497,6,2012,Non Fiction
William P. Young,The Shack: Where Tragedy Confronts Eternity,4.6,19720,8,2009,Fiction
Wizards RPG Team,Player's Handbook (Dungeons & Dragons),4.8,16990,27,2017,Fiction
Zhi Gang Sha,Divine Soul Mind Body Healing and Transmission...,4.6,37,6,2009,Non Fiction

In [12]:
books.groupby('Author').median()

TypeError: agg function failed [how->median,dtype->object]

In [13]:
books.groupby('Author').sum()

,Name,User Rating,Reviews,Price,Year,Genre
Author,,,,,,
Abraham Verghese,Cutting for StoneCutting for Stone,9.2,9732,22,4021,FictionFiction
Adam Gasiewski,Milk and Vine: Inspirational Quotes From Class...,4.4,3113,6,2017,Non Fiction
Adam Mansbach,Go the F**k to Sleep,4.8,9568,9,2011,Fiction
Adir Levy,What Should Danny Do? (The Power to Choose Ser...,4.8,8170,13,2019,Fiction
Admiral William H. McRaven,Make Your Bed: Little Things That Can Change Y...,4.7,10199,11,2017,Non Fiction
...,...,...,...,...,...,...
Walter Isaacson,Leonardo da VinciSteve JobsSteve Jobs,13.7,18668,61,6040,Non FictionNon FictionNon Fiction
William Davis,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",8.8,14994,12,4025,Non FictionNon Fiction
William P. Young,The Shack: Where Tragedy Confronts EternityThe...,9.2,39440,16,4026,FictionFiction
Wizards RPG Team,Player's Handbook (Dungeons & Dragons)Player's...,14.4,50970,81,6054,FictionFictionFiction
Zhi Gang Sha,Divine Soul Mind Body Healing and Transmission...,9.2,257,23,4022,Non FictionNon Fiction

In [15]:
books.groupby('Author').sum().loc['William Davis']

Name           Wheat Belly: Lose the Wheat, Lose the Weight, ...
User Rating                                                  8.8
Reviews                                                    14994
Price                                                         12
Year                                                        4025
Genre                                     Non FictionNon Fiction
Name: William Davis, dtype: object

In [17]:
# Como el indice se modifica cuando agrupo los valores, puedo restablecerlo con reset index
books.groupby('Author').sum().reset_index()

,Author,Name,User Rating,Reviews,Price,Year,Genre
0,Abraham Verghese,Cutting for StoneCutting for Stone,9.2,9732,22,4021,FictionFiction
1,Adam Gasiewski,Milk and Vine: Inspirational Quotes From Class...,4.4,3113,6,2017,Non Fiction
2,Adam Mansbach,Go the F**k to Sleep,4.8,9568,9,2011,Fiction
3,Adir Levy,What Should Danny Do? (The Power to Choose Ser...,4.8,8170,13,2019,Fiction
4,Admiral William H. McRaven,Make Your Bed: Little Things That Can Change Y...,4.7,10199,11,2017,Non Fiction
...,...,...,...,...,...,...,...
243,Walter Isaacson,Leonardo da VinciSteve JobsSteve Jobs,13.7,18668,61,6040,Non FictionNon FictionNon Fiction
244,William Davis,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",8.8,14994,12,4025,Non FictionNon Fiction
245,William P. Young,The Shack: Where Tragedy Confronts EternityThe...,9.2,39440,16,4026,FictionFiction
246,Wizards RPG Team,Player's Handbook (Dungeons & Dragons)Player's...,14.4,50970,81,6054,FictionFictionFiction
247,Zhi Gang Sha,Divine Soul Mind Body Healing and Transmission...,9.2,257,23,4022,Non FictionNon Fiction

In [22]:
# Funciones de agregación. Quiero saber cual es el minimo y el maximo por cada uno.
books.groupby('Author').agg(['min', 'max'])

                                                                         Name  \
                                                                          min
Author
Abraham Verghese                                            Cutting for Stone
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...
Adam Mansbach                                            Go the F**k to Sleep
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...
...                                                                       ...
Walter Isaacson                                             Leonardo da Vinci
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...
William P. Young                  The Shack: Where Tragedy Confronts Eternity
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...

                                                                               \
                                                                          max
Author
Abraham Verghese                                            Cutting for Stone
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...
Adam Mansbach                                            Go the F**k to Sleep
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...
...                                                                       ...
Walter Isaacson                                                    Steve Jobs
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...
William P. Young                  The Shack: Where Tragedy Confronts Eternity
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min
Author
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011
Adir Levy                          4.8  4.8    8170   8170    13  13  2019
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017
...                                ...  ...     ...    ...   ...  ..   ...
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011
William Davis                      4.4  4.4    7497   7497     6   6  2012
William P. Young                   4.6  4.6   19720  19720     8   8  2009
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009

                                        Genre
                             max          min          max
Author
Abraham Verghese            2011      Fiction      Fiction
Adam Gasiewski              2017  Non Fiction  Non Fiction
Adam Mansbach               2011      Fiction      Fiction
Adir Levy                   2019      Fiction      Fiction
Admiral William H. McRaven  2017  Non Fiction  Non Fiction
...                          ...          ...          ...
Walter Isaacson             2017  Non Fiction  Non Fiction
William Davis               2013  Non Fiction  Non Fiction
William P. Young            2017      Fiction      Fiction
Wizards RPG Team            2019      Fiction      Fiction
Zhi Gang Sha                2013  Non Fiction  Non Fiction

[248 rows x 12 columns]

In [21]:
books.groupby('Author').agg(['min', 'max']).reset_index()

                         Author  \

0              Abraham Verghese
1                Adam Gasiewski
2                 Adam Mansbach
3                     Adir Levy
4    Admiral William H. McRaven
..                          ...
243             Walter Isaacson
244               William Davis
245            William P. Young
246            Wizards RPG Team
247                Zhi Gang Sha

                                                  Name  \
                                                   min
0                                    Cutting for Stone
1    Milk and Vine: Inspirational Quotes From Class...
2                                 Go the F**k to Sleep
3    What Should Danny Do? (The Power to Choose Ser...
4    Make Your Bed: Little Things That Can Change Y...
..                                                 ...
243                                  Leonardo da Vinci
244  Wheat Belly: Lose the Wheat, Lose the Weight, ...
245        The Shack: Where Tragedy Confronts Eternity
246             Player's Handbook (Dungeons & Dragons)
247  Divine Soul Mind Body Healing and Transmission...

                                                       User Rating       \
                                                   max         min  max
0                                    Cutting for Stone         4.6  4.6
1    Milk and Vine: Inspirational Quotes From Class...         4.4  4.4
2                                 Go the F**k to Sleep         4.8  4.8
3    What Should Danny Do? (The Power to Choose Ser...         4.8  4.8
4    Make Your Bed: Little Things That Can Change Y...         4.7  4.7
..                                                 ...         ...  ...
243                                         Steve Jobs         4.5  4.6
244  Wheat Belly: Lose the Wheat, Lose the Weight, ...         4.4  4.4
245        The Shack: Where Tragedy Confronts Eternity         4.6  4.6
246             Player's Handbook (Dungeons & Dragons)         4.8  4.8
247  Soul Healing Miracles: Ancient and New Sacred ...         4.6  4.6

    Reviews        Price      Year              Genre
        min    max   min max   min   max          min          max
0      4866   4866    11  11  2010  2011      Fiction      Fiction
1      3113   3113     6   6  2017  2017  Non Fiction  Non Fiction
2      9568   9568     9   9  2011  2011      Fiction      Fiction
3      8170   8170    13  13  2019  2019      Fiction      Fiction
4     10199  10199    11  11  2017  2017  Non Fiction  Non Fiction
..      ...    ...   ...  ..   ...   ...          ...          ...
243    3014   7827    20  21  2011  2017  Non Fiction  Non Fiction
244    7497   7497     6   6  2012  2013  Non Fiction  Non Fiction
245   19720  19720     8   8  2009  2017      Fiction      Fiction
246   16990  16990    27  27  2017  2019      Fiction      Fiction
247      37    220     6  17  2009  2013  Non Fiction  Non Fiction

[248 rows x 13 columns]

In [23]:
books.groupby('Author').agg({'Reviews': ['min', 'max'], 'User Rating': ['sum', 'count']})

                           Reviews        User Rating
                               min    max         sum count
Author
Abraham Verghese              4866   4866         9.2     2
Adam Gasiewski                3113   3113         4.4     1
Adam Mansbach                 9568   9568         4.8     1
Adir Levy                     8170   8170         4.8     1
Admiral William H. McRaven   10199  10199         4.7     1
...                            ...    ...         ...   ...
Walter Isaacson               3014   7827        13.7     3
William Davis                 7497   7497         8.8     2
William P. Young             19720  19720         9.2     2
Wizards RPG Team             16990  16990        14.4     3
Zhi Gang Sha                    37    220         9.2     2

[248 rows x 4 columns]

In [25]:
# Puedo hacer una llave compuesta para la agrupación, multiples combinaciones con la llave de agrupación
books.groupby(['Author', 'Year', 'Genre']).count()

                                   Name  User Rating  Reviews  Price
Author           Year Genre
Abraham Verghese 2010 Fiction         1            1        1      1
                 2011 Fiction         1            1        1      1
Adam Gasiewski   2017 Non Fiction     1            1        1      1
Adam Mansbach    2011 Fiction         1            1        1      1
Adir Levy        2019 Fiction         1            1        1      1
...                                 ...          ...      ...    ...
Wizards RPG Team 2017 Fiction         1            1        1      1
                 2018 Fiction         1            1        1      1
                 2019 Fiction         1            1        1      1
Zhi Gang Sha     2009 Non Fiction     1            1        1      1
                 2013 Non Fiction     1            1        1      1

[493 rows x 4 columns]

In [30]:
books.groupby(level=0)

In [33]:
books.groupby(by=["b"]).sum()

KeyError: 'b'